workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

stages:
  - build
  - format_lint
  - test
  # - deploy

build-job:
  stage: build
  script:
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .

format-job:
  stage: format_lint
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - ruff format --check

lint-job:
  stage: format_lint
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  script:
    - ruff check

test-job:
    stage: test
    image: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    services:
      - name: postgres:17
        variables:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    script:
      - pytest

#deploy-job:
#  stage: deploy
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
