variables:
  IMAGE_CI_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG-ci
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG

workflow:
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v\d+\.\d+\.\d+$/'

stages:
  - build
  - format_lint
  - test
  # - deploy

build-job:
  stage: build
  script:
    - docker build -f ./ci.Dockerfile -t $IMAGE_CI_TAG .

format-job:
  stage: format_lint
  image:
    name: $IMAGE_CI_TAG
    pull_policy: never
  script:
    - ruff format --check

lint-job:
  stage: format_lint
  image:
    name: $IMAGE_CI_TAG
    pull_policy: never
  script:
    - ruff check

test-job:
    stage: test
    image:
      name: $IMAGE_CI_TAG
      pull_policy: never
    services:
      - name: postgres:17
        alias: db
        variables:
          POSTGRES_DB: test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
    script:
      - pytest

#deploy-job:
#  stage: deploy
#  environment: production
#  script:
#    - echo "Deploying application..."
#    - echo "Application successfully deployed."
