services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        ports:
            - "${DB_PORT:-5432}:${DB_PORT:-5432}"
        volumes:
            - pgdata:/var/lib/postgresql/data

    backend:
        build:
            context: ./
            dockerfile: ./dev.Dockerfile
        env_file: ".env"
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - db
            - redis
        ports:
            - "8000:8000"
        volumes:
            - ./alembic.ini:/opt/fastapi_app/alembic.ini:ro
            - ./src:/opt/fastapi_app/src:ro
            - ./src/migrations/versions:/opt/fastapi_app/src/migrations/versions
        command: >
            bash -c "fastapi dev --host 0.0.0.0 --port 8000 src/main.py"

    redis:
        image: redis:8
        ports:
            - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"

volumes:
    pgdata:
