services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASS}
        ports:
            - "${DB_PORT:-5432}:${DB_PORT:-5432}"
        volumes:
            - dev_pg_data:/var/lib/postgresql/data

    redis:
        image: redis:8
        ports:
            - "${REDIS_PORT:-6379}:${REDIS_PORT:-6379}"
        volumes:
            - dev_redis_data:/data

    backend:
        build:
            context: ./
            dockerfile: ./dev.Dockerfile
        env_file: ".env"
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - db
            - redis
        ports:
            - "8000:8000"
        volumes:
            - "dev_media:${LOCAL_MEDIA_ROOT}"
            - ./alembic.ini:/app/alembic.ini:ro
            - ./src/bookings_study:/app/bookings_study:ro
            - ./src/bookings_study/migrations/versions:/app/bookings_study/migrations/versions
        command: >
            bash -c "fastapi dev --host 0.0.0.0 --port 8000 bookings_study/main.py"

    celery_worker:
        build:
            context: ./
            dockerfile: ./dev.Dockerfile
        env_file: ".env"
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - backend
            - redis
        volumes:
            - "dev_media:${LOCAL_MEDIA_ROOT}"
            - ./src/bookings_study:/app/bookings_study:ro
        command: "celery --app=bookings_study.background_tasks.celery.app:celery_app worker -l INFO"

    celery_beat:
        build:
            context: ./
            dockerfile: ./dev.Dockerfile
        env_file: ".env"
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - backend
            - redis
        volumes:
            - "dev_media:${LOCAL_MEDIA_ROOT}"
            - ./src/bookings_study:/app/bookings_study:ro
        command: "celery --app=bookings_study.background_tasks.celery.app:celery_app beat -l INFO"

    nginx:
        image: nginx:stable-alpine
        environment:
            - "LOCAL_MEDIA_ROOT=${LOCAL_MEDIA_ROOT}"
        depends_on:
            - backend
            - celery_worker
            - celery_beat
        ports:
            - "9000:9000"
        volumes:
            - "dev_media:${LOCAL_MEDIA_ROOT}"
            - ./nginx/templates/dev.app.conf.template:/etc/nginx/templates/dev.app.conf.template:ro
            - ./frontend:/app/static

volumes:
    dev_media:
    dev_pg_data:
    dev_redis_data:
