services:
    db:
        image: postgres:17
        environment:
            - POSTGRES_DB=test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        expose:
            - 5432
        volumes:
            - test_pgdata:/var/lib/postgresql/data

    test:
        build:
            context: ./
            dockerfile: ./dev.Dockerfile
        depends_on:
            - db
        expose:
            - 8000
        volumes:
            - ./pytest.ini:/app/pytest.ini:ro
            - ./src:/app/src:ro
            - ./tests:/app/tests:ro
        command: bash -c "pytest"


volumes:
    test_pgdata:
